config/routes.rb
Rails.application.routes.draw do
  resources :participants
  resources :slots
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
  get 'standard', to: 'theme#standard'
  get 'listed', to: 'theme#listed'
  get 'boxed', to: 'theme#boxed'

  get 'events(/:id)/participants' => 'participants#event_participants', as: :event_participants
end

app/models/participant.rb
# == Schema Information
#
# Table name: participants
#
#  id                :integer          not null, primary key
#  affiliation       :string
#  email             :string
#  first_name        :string
#  is_contact_person :boolean
#  last_name         :string
#  telephone         :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  event_id          :integer
#

class Participant < ApplicationRecord
  belongs_to :event, foreign_key: 'event_id', primary_key: 'id'
  validates :event_id, presence: true
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
    @participants = Participant.where(event_id:  params[:event_id])
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to event_participants_path(@participant.event_id), notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def event_participants
    @participants = Participant.where(event_id: params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:first_name, :last_name, :affiliation, :email, :telephone,
                                          :is_contact_person, :event_id)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_with(model: participant, local: true) do |form| %>
  <% if participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ui form">
    <div class="field">
      <label>Event:</label>
      <%= form.collection_select :event_id, Event.order(:title), :id, :title, :prompt => "Select" %>
    </div>
    <div class="two fields">
      <div class="field">
        <%= form.label :first_name %>
        <%= form.text_field :first_name %>
      </div>

      <div class="field">
        <%= form.label :last_name %>
        <%= form.text_field :last_name %>
      </div>
    </div>

    <div class="two fields">
      <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
      </div>

      <div class="field">
        <%= form.label :telephone %>
        <%= form.text_field :telephone %>
      </div>
    </div>
    
    <div class="two fields">
      <div class="field">
        <%= form.label :affiliation %>
        <%= form.text_field :affiliation %>
      </div>
      <div class="field">
        <label>Is contact person?</label>
        <%= form.select(:is_contact_person, options_for_select([['Yes', true], ['No', false]], {:selected => participant.is_contact_person}),:prompt => "Select") %>

      </div>
    </div>

    <%= form.submit "Save", class: "ui button primary" %>
    <% if participant.event.present? %>
      <%= link_to "Cancel", event_path(participant.event), class: "ui red button" %>
    <% else %>
      <%= link_to "Cancel", events_path, class: "ui red button" %>
    <% end %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form', participant: @participant %>

app/views/participants/event_participants.html.erb
<h1>Participants</h1>

<% if @participants.present? %>
  <table class="ui celled table">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Affiliation</th>
        <th>Email</th>
        <th>Telephone</th>
        <th>Is contact person?</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @participants.each do |participant| %>
        <tr>
          <td><%= participant.first_name %></td>
          <td><%= participant.last_name %></td>
          <td><%= participant.affiliation %></td>
          <td><%= participant.email %></td>
          <td><%= participant.telephone %></td>
          <td>
            <% if participant.is_contact_person === true %>
            Yes
            <% else %>
            No
            <% end %>
          </td>
          <td>
            <%= link_to raw("<i class=\"edit outline icon\"></i>"), edit_participant_path(participant), class: "ui mini teal icon button"%>
            <%= link_to raw("<i class=\"trash icon\"></i>"), participant, class: "ui mini red icon button",
                      :method => :delete, :data => {:confirm => 'Are you sure?'} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No Participants</p>
<% end %>

<br>

<%= link_to 'New Participant', new_participant_path, class: "ui orange button" %>
<%= link_to 'Back to Event', :back, class: "ui blue button" %>

app/views/participants/index.html.erb
<h1>Participants</h1>

<table class="ui celled table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Affiliation</th>
      <th>Email</th>
      <th>Telephone</th>
      <th>Is contact person?</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.first_name %></td>
        <td><%= participant.last_name %></td>
        <td><%= participant.affiliation %></td>
        <td><%= participant.email %></td>
        <td><%= participant.telephone %></td>
        <td>
          <% if participant.is_contact_person === true %>
          Yes
          <% else %>
          No
          <% end %>
        </td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path, class: "ui blue button" %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', participant: @participant %>

app/views/participants/show.html.erb
<table class="ui definition table">
  <tbody>
    <tr>
      <td>First Name</td>
      <td><%= @participant.first_name %></td>
    </tr>
      <td>Last Name</td>
      <td><%= @participant.last_name %></td>
    </tr>
      <td>Affiliation</td>
      <td><%= @participant.affiliation %></td>
    </tr>
      <td>Email</td>
      <td><%= @participant.email %></td>
    </tr>
      <td>Telephone</td>
      <td><%= @participant.telephone %></td>
    </tr>
      <td>Is contact person?</td>
      <td>
        <% if @participant.is_contact_person === true %>
        Yes
        <% else %>
        No
        <% end %>
      </td>
  </tbody>
</table>


<%= link_to 'Edit', edit_participant_path(@participant), class: "ui orange button" %>
<%= link_to 'Back to Event', event_path(@participant.event), class: "ui blue button" %>