config/routes.rb
Rails.application.routes.draw do
  resources :participants
  resources :slots
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
  get 'standard', to: 'theme#standard'
  get 'listed', to: 'theme#listed'
  get 'boxed', to: 'theme#boxed'

  get 'events(/:id)/participants' => 'participants#event_participants', as: :event_participants
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id             :integer          not null, primary key
#  description    :text
#  end_date       :date
#  end_time       :time
#  location       :string
#  number_of_days :integer
#  room           :string
#  start_date     :date
#  start_time     :time
#  title          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Event < ApplicationRecord
	has_many  :slots,
            dependent: :destroy,
            foreign_key: 'event_id',
            primary_key: 'id'

  has_many  :participants,
            dependent: :destroy,
            foreign_key: 'event_id',
            primary_key: 'id'

	def number_of_days
		(end_date - start_date).to_i
	end

  def days
    (start_date..end_date).to_a
  end	
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def listed
  end

  def standard
  end

  def boxed
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:id, :title, :description, :start_date, :end_date, :location,
                                    :start_time, :end_time, :room)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="ui form">
    <div class="inline fields">
      <label>Title:</label>
      <%= form.text_field :title, class: "ui input" %>
    </div>
    
    <div class="two fields">
      <div class="field">
        <label>Start Date:</label>
        <%= form.date_field :start_date %>
      </div>

      <div class="field">
        <label>End Date:</label>
        <%= form.date_field :end_date %>
      </div>
    </div>

    <div class="two fields">
      <div class="inline field">
        <label>Start Time:</label>
        <%= form.time_select :start_time, value: "%H:%M" %>
      </div>

      <div class="inline field">
        <label>End Time:</label>
        <%= form.time_select :end_time, value: "%H:%M" %>
      </div>
    </div>
      
    <div class="two fields">
      <div class="field">
        <label>Location:</label>
        <%= form.text_field :location %>
      </div>
      <div class="field">
        <label>Room:</label>
        <%= form.text_field :room %>
      </div>
    </div>
    <div class="field">
      <label>Description:</label>
      <%= form.text_area :description %>
    </div>
    <%= form.submit "Save", class: "ui button primary" %>
    <%= link_to "Cancel", events_path, class: "ui red button" %>
  </div>
<% end %>

app/views/events/_introduction.html.erb
<div class="ui raised segment">
  <div class="ui items">
      <div class="item">
          <div class="content">
            <h1 class="ui blue header"><%= event.title %></h1>
            <div class="ui divider"></div>
            <table class="very basic table">
              <tbody>
                <tr>
                  <td rowspan="2"><i class="map marker alternate big icon"></i></td>
                  <td><%= event.location %></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td rowspan="2"><i class="calendar alternate outline big icon"></td>
                  <td><strong>Starts: </strong><%= event.start_date.to_date %>, <%= event.start_time.strftime("%l:%M %P") %></td>
                </tr>
                <tr>
                  <td><strong>Room: </strong><%= event.room %></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td><strong>Ends: </strong><%= event.end_date.to_date %>, <%= event.end_time.strftime("%l:%M %P") %></td>
                </tr>
              </tbody>
            </table>
            <div class="ui divider"></div>
            <div class="meta"><span class="cinema">Description</span></div>
            <div class="description"><%= markdown(event.description) %></div>
            <div class="ui divider"></div>
            <div class="meta"><span class="cinema">Contact Person</span></div><br />
            <div class="ui celled horizontal list">
              <% event.participants.each do |participant| %>
                <% if participant.is_contact_person === true %>
                  <div class="item">
                    <i class="grey user icon"></i>
                    <%= participant.first_name %> <%= participant.last_name %><br /><br />
                    <i class="grey send icon"></i>
                    <a href="mailto: <% participant.email %>"><%= participant.email %></a><br /><br />
                    <i class="grey phone icon"></i>
                    <a href="tel: <% participant.telephone %>"><%= participant.telephone %></a>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/events/_slot_listed.html.erb
<div class="row">
  <div class="two wide column">
    <p><%= slot.start_time.strftime("%l:%M %P") %> - <%= slot.end_time.strftime("%l:%M %P") %></p>
  </div>
  <div class="fourteen wide column">
    <div class="ui segment">
    	<div class="ui items">
    	<div class="item">
		    <div class="content">
		    	<%= link_to slot.title, edit_slot_path(slot.id), class: "header"%>
		      <p class="ui right floated"><%= slot.speaker %></p>
		      <div class="extra">
			      <br />
			      <div class="ui left floated"><i class="map marker alternate icon"></i> <%= slot.location %>, Room: <%= slot.room %></div>
			      <div class="ui right floated"><i class="clock outline icon"></i> <%= slot.duration %> minutes</div>
		      </div>
		      <div class="ui divider"></div>
			      <%= link_to raw("<i class=\"edit outline icon\"></i>"), edit_slot_path(slot.id), class: "ui right floated mini teal icon button"%>
          	<%= link_to raw("<i class=\"trash icon\"></i>"), slot, class: "ui right floated mini red icon button",
                      :method => :delete, :data => {:confirm => 'Are you sure?'} %>
		    </div>
		  </div>
  	</div>
	</div>
</div>
</div>

app/views/events/_timetable.html.erb
<div class="ui container">
	<div></div>
  <h2 class="ui blue header center aligned">Timetable</h2>
  <div class="ui divider"></div>
	<div class="ui tabular menu">
		<% event.days.each do |day| %>
			<div class="item <%= 'active' if day === event.days.first %>" data-tab="tab-name-<%=day.to_s %>">Day <%= event.days.find_index(day) + 1 %></div>
		<% end %>
	</div>
	<% event.days.each do |day| %>
		<div class="ui <%= 'active' if day === event.days.first %> tab" data-tab="tab-name-<%= day.to_s%>">
			<div class="ui internally celled grid">
				<% @event.slots.each do |slot| %>
					<% if day === slot.date%>
						<%= render 'slot_listed', slot: slot %>
					<% end %>
				<% end %>
		  </div>
		</div>
	<% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<div class="ui divided items">
  <% @events.each do |event| %>
    <div class="item">
      <div class="content">
        <%= link_to event.title, event, class: "ui large blue header" %>
        <!-- <div class="description">
          <%= markdown(event.description) %>
        </div> -->
        <div class="extra">
          <div class="ui label"><i class="map marker alternate icon"></i> <%= event.location %></div>
          <div class="ui label"><i class="calendar alternate outline icon"></i> <%= event.start_date.to_date %></div>
          <div class="ui label"><i class="clock outline icon"></i> <%= event.start_time.strftime("%l:%M %P") %></div>
          <%= link_to raw("<i class=\"edit outline icon\"></i>"), edit_event_path(event), class: "ui right floated mini teal icon button"%>
          <%= link_to raw("<i class=\"trash icon\"></i>"), event, class: "ui right floated mini red icon button",
                      :method => :delete, :data => {:confirm => 'Are you sure?'} %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/events/listed.html.erb
<%= link_to "Create Slot", new_slot_path, class: "ui orange button" %>
<%= link_to "View Participants", event_participants_path(@event.id), class: "ui violet button" %>
<%= link_to "Edit", edit_event_path(@event), class: "ui right floated teal button"%>
<%= link_to "Delete", @event, class: "ui right floated red button",
                      :method => :delete, :data => {:confirm => 'Are you sure?'} %>

<%= render 'introduction', event: @event %>

<%= render 'timetable', event: @event %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<%= link_to "Create Slot", new_slot_path, class: "ui orange button" %>
<%= link_to "View Participants", event_participants_path(@event.id), class: "ui violet button" %>
<%= link_to "Edit", edit_event_path(@event), class: "ui right floated teal button"%>
<%= link_to "Delete", @event, class: "ui right floated red button",
                      :method => :delete, :data => {:confirm => 'Are you sure?'} %>

<%= render 'introduction', event: @event %>

<%= render 'timetable', event: @event %>