config/routes.rb
Rails.application.routes.draw do
  resources :participants
  resources :slots
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
  get 'standard', to: 'theme#standard'
  get 'listed', to: 'theme#listed'
  get 'boxed', to: 'theme#boxed'

  get 'events(/:id)/participants' => 'participants#event_participants', as: :event_participants
end

app/views/layouts/_event_introduction.html.erb
<div class="ui raised segment">
  <div class="ui items">
      <div class="item">
          <div class="content">
            <a class="header">Title of Event</a>
            <div class="meta">
              <span class="cinema">Description</span>
            </div>
            <div class="description">
              <p>This is description</p>
            </div>
            <div class="extra">
             <br />
             <div class="ui left floated">Leonardo-Campus 18, 48151 Münster</div>
             <div class="ui right floated">2019.02.02 to 2019.02.03</div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
  

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to 'All Events', events_path, class: "item #{'active' if current_page?(events_path)}"%>
<%= link_to raw("<i class=\"write icon\"></i> New Event"), new_event_path, class: "item #{'active' if current_page?(new_event_path)}"%>
<div class="ui dropdown item">
  Change View <i class="dropdown icon"></i>
  <div class="menu">
    <%= link_to 'Standard', standard_path, class: "item #{'active' if current_page?(standard_path)}"%>
    <%= link_to 'Listed', listed_path,  class: "item #{'active' if current_page?(listed_path)}" %>
    <%= link_to 'Boxed', boxed_path,  class: "item #{'active' if current_page?(boxed_path)}" %>
  </div>
</div>
<div class="right menu">
  <div class="item">
      <div class="ui primary inverted button">Logout</div>
  </div>
  <h2 class="item"><i class="snowflake outline icon"></i> ERCIS-EMS</h2>
</div>

<%
=begin
<%= link_to 'All Events', events_path, :class => "item" %>
<div class="ui dropdown item">
  Change View <i class="dropdown icon"></i>
  <div class="menu">
    <a class="item">Standard</a>
    <a class="item">Listed</a>
    <a class="item">Boxed</a>
  </div>
</div>
<%= link_to raw("<i class=\"write icon\"></i> New Event"), new_event_path, :class => "item" %>
<div class="right menu">
  <div class="item">
      <div class="ui primary inverted button">Login</div>
  </div>
  <h2 class="item"><i class="snowflake outline icon"></i>  ERCIS-EMS</h2>
</div>
=end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ErcisEms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="ui blue inverted segment" style="border-radius: 0 !important">
      <div class="ui inverted secondary large menu">
        <div class="ui container">
          <%= render 'layouts/navigation' %>
        </div>
      </div>
    </div>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <div id="footer"></div>
  </body>
</html>